### ISSUE TITLE
Are sounds playing on the right channel?

### ISSUE THREAD

**Issue by olilan1** [olilan1/pf2e-creature-sounds#8]
Sounds currently play on the "interface" channel as that's the default. Is that right, or should it be the "environment" channel?

**Comment by mustangsami** [comment]
https://github.com/olilan1/pf2e-creature-sounds/commit/43a4ecfdde29767f63ffe2b25ece83cd2590cb64

**Comment by mustangsami** [comment]
AA also uses interface so maybe it's ok?
